//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Model.DMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ContentTypeID { get; set; }
        public string FilePath { get; set; }
        public string CodePath { get; set; }
        public string DocCreatedBy { get; set; }
        public int UserID { get; set; }
        public int TechnologyID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual LookupDetail LookupDetail { get; set; }
        public virtual LookupDetail LookupDetail1 { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
