//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Model.DMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupDetail
    {
        public LookupDetail()
        {
            this.DocumentDetails = new HashSet<DocumentDetail>();
            this.DocumentDetails1 = new HashSet<DocumentDetail>();
            this.SkillDetails = new HashSet<SkillDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> LookupMasterId { get; set; }
        public bool Active { get; set; }
        public string Name { get; set; }
    
        public virtual LookupMaster LookupMaster { get; set; }
        public virtual ICollection<DocumentDetail> DocumentDetails { get; set; }
        public virtual ICollection<DocumentDetail> DocumentDetails1 { get; set; }
        public virtual ICollection<SkillDetail> SkillDetails { get; set; }
    }
}
