//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Model.DMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillDetail
    {
        public int Id { get; set; }
        public int LookupDetailsId { get; set; }
        public bool Active { get; set; }
        public string Name { get; set; }
    
        public virtual LookupDetail LookupDetail { get; set; }
    }
}
