//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Model.DMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public UserLogin()
        {
            this.DocumentDetails = new HashSet<DocumentDetail>();
            this.Tokens = new HashSet<Token>();
            this.Tokens1 = new HashSet<Token>();
            this.UserSkills = new HashSet<UserSkill>();
        }
    
        public int Id { get; set; }
        public string ServerName { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<DocumentDetail> DocumentDetails { get; set; }
        public virtual ICollection<Token> Tokens { get; set; }
        public virtual ICollection<Token> Tokens1 { get; set; }
        public virtual ICollection<UserSkill> UserSkills { get; set; }
    }
}
