//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Model.DMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSkill
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string TechnologyId { get; set; }
        public string SkillId { get; set; }
    
        public virtual UserLogin UserLogin { get; set; }
    }
}
